# Generated by Django 4.2.29 on 2026-03-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_fts5_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('replacement_text', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('version_at_change', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='documents.document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
